### ISSUE TITLE
Header Layout 

### ISSUE THREAD

**Issue by Ahmedshk** [aliahmed922/utility_navigator#1]
Make the landing page header layout having 4 buttons on right side 
twc - cox - charter - login

**Comment by Ahmedshk** [comment]
Please remove register button from home page as we all only allow sign up at the time of purchasing

**Comment by aliahmed922** [comment]
@Ahmedshk links are already there

**Comment by Ahmedshk** [comment]
Please remove register button from home page as we all only allow sign up at the time of purchasing

**Comment by aliahmed922** [comment]
@Ahmedshk Done
